// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttpvxklecvqlzvrlnkri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0cHZ4a2xlY3ZxbHp2cmxua3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA3MjUsImV4cCI6MjA3MTMwNjcyNX0.GgMdpkXCZzVUuXt0bLN6ZysJb5MvsIQEwP4zY0wIKH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});